=== ciax/ciax-xml/schema/adb.xsd
<?xml version="1.0" encoding="shift_jis"?>
<xsd:schema targetNamespace="http://ciax.sum.naoj.org/ciax-xml/adb" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:adb="http://ciax.sum.naoj.org/ciax-xml/adb" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://www.w3.org/2001/XMLSchema">
  <xsd:element name="adb">
    <xsd:complexType>
      <xsd:sequence>
        <xsd:element ref="adb:object" minOccurs="1" maxOccurs="unbounded" />
      </xsd:sequence>
    </xsd:complexType>
  </xsd:element>
  <xsd:attributeGroup name="id_attr">
    <xsd:attribute name="id" type="xsd:string" use="optional" />
    <xsd:attribute name="label" type="xsd:string" use="optional"></xsd:attribute>
    <xsd:attribute name="ref" type="xsd:string" use="optional" />
  </xsd:attributeGroup>
  <xsd:element name="object">
    <xsd:complexType>
      <xsd:sequence>
        <xsd:element ref="adb:comm" minOccurs="1" maxOccurs="1" />
        <xsd:element ref="adb:command" minOccurs="0" maxOccurs="1"></xsd:element>
        <xsd:element ref="adb:status" minOccurs="1" maxOccurs="1" />
      </xsd:sequence>
      <xsd:attributeGroup ref="adb:id_attr"></xsd:attributeGroup>
    </xsd:complexType>
  </xsd:element>
  <xsd:element name="comm">
    <xsd:complexType>
      <xsd:sequence>
        <xsd:element ref="adb:class" minOccurs="1" maxOccurs="1"></xsd:element>
        <xsd:element ref="adb:client"></xsd:element>
        <xsd:element ref="adb:server"></xsd:element>
      </xsd:sequence>
    </xsd:complexType>
  </xsd:element>
  <xsd:element name="class" type="xsd:string"></xsd:element>
  <xsd:element name="client" type="xsd:string"></xsd:element>
  <xsd:element name="server" type="xsd:string" />
  <!--Share-->
  <xsd:element name="repeat">
    <xsd:complexType>
      <xsd:choice>
        <xsd:element minOccurs="1" maxOccurs="unbounded" ref="adb:title" />
        <xsd:element ref="adb:group" minOccurs="1" maxOccurs="unbounded"></xsd:element>
      </xsd:choice>
      <xsd:attribute name="from" use="required" type="xsd:int" />
      <xsd:attribute name="to" use="required" type="xsd:int" />
      <xsd:attribute name="format" type="xsd:string" />
      <xsd:attribute name="counter" type="xsd:string" />
    </xsd:complexType>
  </xsd:element>
  <!--command select-->
  <xsd:element name="command">
    <xsd:complexType>
      <xsd:sequence>
        <xsd:element ref="adb:session" minOccurs="1" maxOccurs="unbounded" />
      </xsd:sequence>
    </xsd:complexType>
  </xsd:element>
  <xsd:element name="session">
    <xsd:complexType>
      <xsd:attributeGroup ref="adb:id_attr"></xsd:attributeGroup>
    </xsd:complexType>
  </xsd:element>
  <!--status-->
  <xsd:element name="status">
    <xsd:complexType>
      <xsd:choice minOccurs="1" maxOccurs="unbounded">
        <xsd:element ref="adb:group"></xsd:element>
        <xsd:element ref="adb:repeat"></xsd:element>
      </xsd:choice>
      <xsd:attribute name="ref" type="xsd:string" use="optional" />
    </xsd:complexType>
  </xsd:element>
  <xsd:element name="group">
    <xsd:complexType>
      <xsd:choice minOccurs="1" maxOccurs="unbounded">
        <xsd:element ref="adb:repeat" />
        <xsd:element ref="adb:title" />
      </xsd:choice>
      <xsd:attribute name="label" type="xsd:string" use="optional" />
      <xsd:attribute name="ref" type="xsd:string" use="optional" />
    </xsd:complexType>
  </xsd:element>
  <xsd:element name="title">
    <xsd:complexType>
      <xsd:simpleContent>
        <xsd:extension base="xsd:string">
          <xsd:attribute name="ref" type="xsd:string" use="required" />
          <xsd:attribute name="symbol" type="xsd:string" />
          <xsd:attribute name="level" type="xsd:string" />
        </xsd:extension>
      </xsd:simpleContent>
    </xsd:complexType>
  </xsd:element>
</xsd:schema>

=== ciax/ciax-xml/adb-crt.xml
<?xml version="1.0" encoding="iso-8859-1"?>
<adb xsi:schemaLocation="http://ciax.sum.naoj.org/ciax-xml/schema/adb.xsd" xmlns="http://ciax.sum.naoj.org/ciax-xml/adb" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
  <object id="crt" label="Cart PLC">
    <comm>
      <class>mel</class>
      <client>socat - udp:cart3:5000</client>
      <server>socat - udp-l:25101,reuseaddr,fork</server>
    </comm>
    <command>
      <session id="upd" label="Regular status update"></session>
      <session id="start_run" label="Running Start"></session>
      <session id="start_jak" label="Jacking Start"></session>
      <session id="clear_trg" label="Jacking Start"></session>
      <session id="set_fwd" label="Set Tag to Forward"></session>
      <session id="set_run1" label="Run to Tag 1"></session>
      <session id="set_jak1" label="Jack UP Level 1"></session>
      <session id="pause" label="Pause"></session>
      <session id="emstop" label="Emergency Stop"></session>
      <session id="resume" label="Resume from Pause"></session>
    </command>
    <status>
      <group>
        <title ref="ecode" symbol="mel:ecode">EXIT CODE</title>
        <title ref="rdy" symbol="normal">READY</title>
        <title ref="pse" symbol="warn">PAUSE</title>
        <title ref="emg" symbol="alarm">ENERGENCY</title>
        <title ref="stp" symbol="warn">STOP</title>
      </group>
      <group>
        <title ref="run" symbol="normal">RUNNING</title>
        <title ref="jak" symbol="normal">JACKING</title>
        <title ref="con" symbol="normal">CHARGING</title>
        <title ref="flt" symbol="alarm">Fault</title>
      </group>
      <group>
        <title ref="msr" symbol="normal">Right Motor Servo</title>
        <title ref="msl" symbol="normal">Left Motor Servo</title>
      </group>
      <group>
        <title ref="jd1" symbol="normal">Jack Motor1 Servo</title>
        <title ref="jd2" symbol="normal">Jack Motor2 Servo</title>
      </group>
      <group>
        <title ref="jd3" symbol="normal">Jack Motor3 Servo</title>
        <title ref="jd4" symbol="normal">Jack Motor4 Servo</title>
      </group>
      <group>
        <title ref="mdar" level="mel:motor">Rignt Motor D/A</title>
        <title ref="mdal" level="mel:motor">Left Motor D/A</title>
      </group>
      <group>
        <title ref="bvl" level="mel:battery">Battery Voltage</title>
        <title ref="ist" symbol="mel:inst">Instrument</title>
      </group>
      <group>
        <title ref="cpos">Current Position</title>
        <title ref="dpos">Destination Position</title>
      </group>
      <group>
        <title ref="jpos" symbol="mel:jpos">Jack Position</title>
      </group>
    </status>
  </object>
</adb>

=== ciax/ciax-xml/adb-ml1.xml
<?xml version="1.0" encoding="iso-8859-1"?>
<adb xsi:schemaLocation="http://ciax.sum.naoj.org/ciax-xml/schema/adb.xsd" xmlns="http://ciax.sum.naoj.org/ciax-xml/adb" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
  <object id="ml1" label="MOIRCS Temperature 1">
    <comm>
      <class>lk8</class>
      <client>socat - tcp:celaeno:4005</client>
      <server>socat - udp-l:24105,reuseaddr,fork</server>
    </comm>
    <command>
      <session id="upd" label="Update Status" />
    </command>
    <status>
      <group>
        <title ref="ch1">MosCold2</title>
        <title ref="ch2">MosCold1</title>
        <title ref="ch3">Mask</title>
        <title ref="ch4">Wheel</title>
      </group>
      <group>
        <title ref="ch5">D1(NONE)</title>
        <title ref="ch6">D2(NONE)</title>
        <title ref="ch7">ChipBox1</title>
        <title ref="ch8">Det1</title>
      </group>
      <group>
        <title ref="sp">SetPoint1 (K)</title>
        <title ref="htr">HeaterPower1(%)</title>
      </group>
    </status>
  </object>
</adb>

=== ciax/ciax-xml/adb-mt1.xml
<?xml version="1.0" encoding="iso-8859-1"?>
<adb xsi:schemaLocation="http://ciax.sum.naoj.org/ciax-xml/schema/adb.xsd" xmlns="http://ciax.sum.naoj.org/ciax-xml/adb" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
  <object id="mt1" label="MOIRCS Pressure Main" ref="mt3">
    <comm>
      <class>tpg</class>
      <client>socat - tcp:celaeno:4009</client>
      <server>socat - udp-l:24109,reuseaddr,fork</server>
    </comm>
    <command>
      <session id="upd" label="Update Status" />
    </command>
    <status>
      <group>
        <title ref="st1">Main Dewar Stat</title>
        <title ref="ch1">Main Dewar (Torr)</title>
      </group>
    </status>
  </object>
</adb>

=== ciax/ciax-xml/adb-cri.xml
<?xml version="1.0" encoding="iso-8859-1"?>
<adb xsi:schemaLocation="http://ciax.sum.naoj.org/ciax-xml/schema/adb.xsd" xmlns="http://ciax.sum.naoj.org/ciax-xml/adb" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
  <object id="cri" label="IR Compressor Room Reserve">
    <comm>
      <class>bbe</class>
      <client>socat - tcp:ltc-i:4003</client>
      <server>socat - udp-l:25107,reuseaddr,fork</server>
    </comm>
    <command>
      <session id="upd" label="Update Status" ref="upd"></session>
      <session id="x0on" label="X0 ON" ref="x0on"></session>
      <session id="x0off" label="X0 OFF" ref="x0off"></session>
      <session id="x1on" label="X1 ON" ref="x1on"></session>
      <session id="x1off" label="X1 OFF" ref="x1off"></session>
      <session id="x2on" label="X2 ON" ref="x2on"></session>
      <session id="x2off" label="X2 OFF" ref="x2off"></session>
      <session id="x3on" label="X3 ON" ref="x3on"></session>
      <session id="x3off" label="X3 OFF" ref="x3off"></session>
    </command>
    <status>
      <group label="">
        <title ref="x0sw">X0 SWITCH</title>
        <title ref="x0dr">X0 DRIVE</title>
      </group>
      <group label="">
        <title ref="x0tm" symbol="normal">X0 TEMP ALARM</title>
        <title ref="x0pr" symbol="normal">X0 PRESSURE ALARM</title>
      </group>
      <group label="">
        <title ref="x1sw" symbol="normal">X1 SWITCH</title>
        <title ref="x1dr" symbol="normal">X1 DRIVE</title>
      </group>
      <group label="">
        <title ref="x1tm" symbol="normal">X1 TEMP ALARM</title>
        <title ref="x1pr" symbol="normal">X1 PRESSURE ALARM</title>
      </group>
      <group label="">
        <title ref="x2sw" symbol="normal">X2 SWITCH</title>
        <title ref="x2dr" symbol="normal">X2 DRIVE</title>
      </group>
      <group label="">
        <title ref="x2tm" symbol="normal">X2 TEMP ALARM</title>
        <title ref="x2pr" symbol="normal">X2 PRESSURE ALARM</title>
      </group>
      <group label="">
        <title ref="x3sw" symbol="normal">X3 SWITCH</title>
        <title ref="x3dr" symbol="normal">X3 DRIVE</title>
      </group>
      <group label="">
        <title ref="x3tm" symbol="normal">X3 TEMP ALARM</title>
        <title ref="x3pr" symbol="normal">X3 PRESSURE ALARM</title>
      </group>
    </status>
  </object>
</adb>

=== ciax/ciax-xml/adb-dts.xml
<?xml version="1.0" encoding="iso-8859-1"?>
<adb xsi:schemaLocation="http://ciax.sum.naoj.org/ciax-xml/schema/adb.xsd" xmlns="http://ciax.sum.naoj.org/ciax-xml/adb" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
  <object id="dts" label="TSC Control">
    <comm>
      <class>oss</class>
      <client>socat - tcp:cxws:9999</client>
      <server>socat - udp-l:25105,reuseaddr,fork</server>
    </comm>
    <command>
      <session id="upd" label="Update Status"></session>
      <session id="login" label="Login"></session>
      <session id="logout" label="Logout"></session>
      <session id="request" label="Start TCP Status Request"></session>
      <session id="startup" label="Start Up CIAX operation"></session>
      <session id="shutdown" label="Shutdown CIAX operation"></session>
      <session id="moircs" label="Set IID MOIRCS"></session>
      <session id="focas" label="Set IID FOCAS"></session>
      <session id="comics" label="Set IID COMICS"></session>
    </command>
    <status>
      <group label="">
        <title ref="exit">Exit Code</title>
        <title ref="rts" symbol="oss:rsel">ROT SEL</title>
        <title ref="iid" symbol="oss:inst">CAS INST ID</title>
        <title ref="login" symbol="login">Login Status</title>
      </group>
      <group label="">
        <title ref="rpw" level="oss:rpw">ROT DRIVE</title>
        <title ref="jpw" symbol="normal">JAK DRIVE</title>
        <title ref="nfb" symbol="alarm">BOLT NFB TRIP</title>
        <title ref="rps" symbol="oss:rps">ROT POS SENSOR</title>
      </group>
      <group label="">
        <title ref="stw" symbol="off-warn">EL STOW</title>
        <title ref="stp" symbol="off-warn">EL 90 STOW</title>
      </group>
    </status>
  </object>
</adb>

=== ciax/ciax-xml/adb-cci.xml
<?xml version="1.0" encoding="iso-8859-1"?>
<adb xsi:schemaLocation="http://ciax.sum.naoj.org/ciax-xml/schema/adb.xsd" xmlns="http://ciax.sum.naoj.org/ciax-xml/adb" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
  <object id="cci" label="IR Helium Compressor Control" ref="cri">
    <comm>
      <class>bbe</class>
      <client>socat - tcp:ltc-i:4002</client>
      <server>socat - udp-l:25105,reuseaddr,fork</server>
    </comm>
    <command>
      <session id="upd" label="Update Status" ref="upd" />
      <session id="c2on" label="CAS2(S1) ON" ref="x0on" />
      <session id="c2off" label="CAS2(S1) OFF" ref="x0off" />
      <session id="c1on" label="CAS1(S2) ON" ref="x1on" />
      <session id="c1off" label="CAS1(S2) OFF" ref="x1off" />
      <session id="m2on" label="MOIRCS CR(S8) ON" ref="x2on" />
      <session id="m2off" label="MOIRCS CR(S8) OFF" ref="x2off" />
      <session id="m1on" label="MOIRCS MAIN(S9) ON" ref="x3on" />
      <session id="m1off" label="MOIRCS MAIN(S9) OFF" ref="x3off" />
      <session id="cmon" label="CAS MOIRCS/MAIN ON" ref="x0on" />
      <session id="cmoff" label="CAS MOIRCS/MAIN OFF" ref="x0off" />
      <session id="ccon" label="CAS MOIRCS/CR ON" ref="x1on" />
      <session id="ccoff" label="CAS MOIRCS/CR OFF" ref="x1off" />
      <session id="caon" label="CAS BOTH HC ON" ref="x12on" />
      <session id="caoff" label="CAS BOTH HC OFF" ref="x12off" />
      <session id="maon" label="MOIRCS BOTH ON" ref="x34on" />
      <session id="maoff" label="MOIRCS BOTH OFF" ref="x34off" />
    </command>
    <status>
      <group>
        <title ref="x0sw" symbol="off-warn">CAS2(S1)(CIAO) SWITCH</title>
        <title ref="x0dr" symbol="off-warn">CAS2(S1)(CIAO) DRIVE</title>
      </group>
      <group>
        <title ref="x0tm" symbol="alarm">CAS2(S1)(CIAO) TEMP</title>
        <title ref="x0pr" symbol="alarm">CAS2(S1)(CIAO) PRESSURE</title>
      </group>
      <group>
        <title ref="x1sw" symbol="off-warn">CAS1(S2)(MOIRCS/MAIN) SWITCH</title>
        <title ref="x1dr" symbol="off-warn">CAS1(S2)(MOIRCS/MAIN) DRIVE</title>
      </group>
      <group>
        <title ref="x1tm" symbol="alarm">CAS1(S2)(MOIRCS/MAIN) TEMP</title>
        <title ref="x1pr" symbol="alarm">CAS1(S2)(MOIRCS/MAIN) PRESSURE</title>
      </group>
      <group>
        <title ref="x2sw" symbol="off-warn">MOIRCS/CR(S8) SWITCH</title>
        <title ref="x2dr" symbol="off-warn">MOIRCS/CR(S8) DRIVE</title>
      </group>
      <group>
        <title ref="x2tm" symbol="alarm">MOIRCS/CR(S8) TEMP</title>
        <title ref="x2pr" symbol="alarm">MOIRCS/CR(S8) PRESSURE</title>
      </group>
      <group>
        <title ref="x3sw" symbol="off-warn">MOIRCS/MAIN(S9) SWITCH</title>
        <title ref="x3dr" symbol="off-warn">MOIRCS/MAIN(S9) DRIVE</title>
      </group>
      <group>
        <title ref="x3tm" symbol="alarm">MOIRCS/MAIN(S9) TEMP</title>
        <title ref="x3pr" symbol="alarm">MOIRCS/MAIN(S9) PRESSURE</title>
      </group>
    </status>
  </object>
</adb>

=== ciax/ciax-xml/adb-mt3.xml
<?xml version="1.0" encoding="iso-8859-1"?>
<adb xsi:schemaLocation="http://ciax.sum.naoj.org/ciax-xml/schema/adb.xsd" xmlns="http://ciax.sum.naoj.org/ciax-xml/adb" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
  <object id="mt3" label="MOIRCS Pressure Pump">
    <comm>
      <class>tpg</class>
      <client>socat - tcp:celaeno:4011</client>
      <server>socat - udp-l:24111,reuseaddr,fork</server>
    </comm>
    <command>
      <session id="upd" label="Update Status"></session>
    </command>
    <status>
      <group>
        <title ref="st1" symbol="tpg:stat">Turbo Pump Stat</title>
        <title ref="ch1">Turbo Pump (Torr)</title>
      </group>
      <group>
        <title ref="st2" symbol="tpg:stat">Scroll Pump Stat</title>
        <title ref="ch2">Scroll Pump (Torr)</title>
      </group>
    </status>
  </object>
</adb>

=== ciax/ciax-xml/adb-mh1.xml
<?xml version="1.0" encoding="iso-8859-1"?>
<adb xsi:schemaLocation="http://ciax.sum.naoj.org/ciax-xml/schema/adb.xsd" xmlns="http://ciax.sum.naoj.org/ciax-xml/adb" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
  <object id="mh1" label="MOIRCS Ext Heater 1">
    <comm>
      <class>psp</class>
      <client>socat - tcp:merope:59999</client>
      <server>socat - udp-l:24201,reuseaddr,fork</server>
    </comm>
    <command>
      <session id="upd" label="Update Status"></session>
      <session id="setlmt" label="Set Limit 20V/5A/100W"></session>
      <session id="setv" label="Set Voltage 0-50[V]"></session>
      <session id="setp" label="Set Power 0-100[W]"></session>
    </command>
    <status>
      <group>
        <title ref="vol">OUTPUT (V)</title>
        <title ref="amp">OUTPUT (A)</title>
        <title ref="wat">OUTPUT (W)</title>
      </group>
      <group>
        <title ref="vl">Limit (V)</title>
        <title ref="il">Limit (A)</title>
        <title ref="pl">Limit (W)</title>
      </group>
      <group>
        <title ref="sw" symbol="warn">OUTPUT ON/OFF</title>
        <title ref="tmp" symbol="alarm">OverHeat</title>
      </group>
      <group>
        <title ref="kn1" symbol="normal">Wheel Knov Fine</title>
        <title ref="kn2" symbol="normal">Wheel Knov Unlock</title>
      </group>
      <group>
        <title ref="rem" symbol="normal">REMOTE</title>
        <title ref="loc" symbol="normal">Local Lock</title>
      </group>
    </status>
  </object>
</adb>
