=== ciax/ciax-xml/schema/adb.xsd
<?xml version="1.0" encoding="shift_jis"?>
<xsd:schema targetNamespace="http://ciax.sum.naoj.org/ciax-xml/adb" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:adb="http://ciax.sum.naoj.org/ciax-xml/adb" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://www.w3.org/2001/XMLSchema">
  <xsd:element name="adb">
    <xsd:complexType>
      <xsd:sequence>
        <xsd:element ref="adb:object" minOccurs="1" maxOccurs="unbounded" />
      </xsd:sequence>
    </xsd:complexType>
  </xsd:element>
  <xsd:attributeGroup name="id_attr">
    <xsd:attribute name="id" type="xsd:string" use="optional" />
    <xsd:attribute name="label" type="xsd:string" use="optional"></xsd:attribute>
    <xsd:attribute name="ref" type="xsd:string" use="optional" />
  </xsd:attributeGroup>
  <xsd:element name="object">
    <xsd:complexType>
      <xsd:sequence>
        <xsd:element ref="adb:comm" minOccurs="1" maxOccurs="1" />
        <xsd:element ref="adb:command" minOccurs="0" maxOccurs="1"></xsd:element>
        <xsd:element ref="adb:status" minOccurs="1" maxOccurs="1" />
      </xsd:sequence>
      <xsd:attributeGroup ref="adb:id_attr"></xsd:attributeGroup>
    </xsd:complexType>
  </xsd:element>
  <xsd:element name="comm">
    <xsd:complexType>
      <xsd:sequence>
        <xsd:element ref="adb:class" minOccurs="1" maxOccurs="1"></xsd:element>
        <xsd:element ref="adb:client"></xsd:element>
        <xsd:element ref="adb:server"></xsd:element>
      </xsd:sequence>
    </xsd:complexType>
  </xsd:element>
  <xsd:element name="class" type="xsd:string"></xsd:element>
  <xsd:element name="client" type="xsd:string"></xsd:element>
  <xsd:element name="server" type="xsd:string" />
  <!--Share-->
  <xsd:element name="repeat">
    <xsd:complexType>
      <xsd:choice>
        <xsd:element minOccurs="1" maxOccurs="unbounded" ref="adb:title" />
        <xsd:element ref="adb:group" minOccurs="1" maxOccurs="unbounded"></xsd:element>
      </xsd:choice>
      <xsd:attribute name="from" use="required" type="xsd:int" />
      <xsd:attribute name="to" use="required" type="xsd:int" />
      <xsd:attribute name="format" type="xsd:string" />
      <xsd:attribute name="counter" type="xsd:string" />
    </xsd:complexType>
  </xsd:element>
  <!--command select-->
  <xsd:element name="command">
    <xsd:complexType>
      <xsd:sequence>
        <xsd:element ref="adb:session" minOccurs="1" maxOccurs="unbounded" />
      </xsd:sequence>
    </xsd:complexType>
  </xsd:element>
  <xsd:element name="session">
    <xsd:complexType>
      <xsd:attributeGroup ref="adb:id_attr"></xsd:attributeGroup>
    </xsd:complexType>
  </xsd:element>
  <!--status-->
  <xsd:element name="status">
    <xsd:complexType>
      <xsd:choice minOccurs="1" maxOccurs="unbounded">
        <xsd:element ref="adb:group"></xsd:element>
        <xsd:element ref="adb:repeat"></xsd:element>
      </xsd:choice>
      <xsd:attribute name="ref" type="xsd:string" use="optional" />
    </xsd:complexType>
  </xsd:element>
  <xsd:element name="group">
    <xsd:complexType>
      <xsd:choice minOccurs="1" maxOccurs="unbounded">
        <xsd:element ref="adb:repeat" />
        <xsd:element ref="adb:title" />
      </xsd:choice>
      <xsd:attribute name="label" type="xsd:string" use="optional" />
      <xsd:attribute name="ref" type="xsd:string" use="optional" />
    </xsd:complexType>
  </xsd:element>
  <xsd:element name="title">
    <xsd:complexType>
      <xsd:simpleContent>
        <xsd:extension base="xsd:string">
          <xsd:attribute name="ref" type="xsd:string" use="required" />
          <xsd:attribute name="symbol" type="xsd:string" />
          <xsd:attribute name="level" type="xsd:string" />
        </xsd:extension>
      </xsd:simpleContent>
    </xsd:complexType>
  </xsd:element>
</xsd:schema>

=== ciax/ciax-xml/adb-mix.xml
<?xml version="1.0" encoding="iso-8859-1"?>
<adb xsi:schemaLocation="http://ciax.sum.naoj.org/ciax-xml/schema/adb.xsd" xmlns="http://ciax.sum.naoj.org/ciax-xml/adb" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
  <object id="mix" label="MOIRCS Turret">
    <comm>
      <class>ixe</class>
      <client>socat - tcp:celaeno:4007</client>
      <server>socat - udp-l:24107,reuseaddr,fork</server>
    </comm>
    <status>
      <group>
        <title ref="rdy" symbol="off-warn">Comm Ready</title>
        <title ref="srq" symbol="off-warn">SRQ</title>
        <title ref="pme" symbol="alarm">Program Error</title>
        <title ref="pse" symbol="alarm">Power Stage Error</title>
        <title ref="oes" symbol="alarm">ONE EM Stop</title>
        <title ref="ees" symbol="alarm">EXT EM Stop</title>
      </group>
      <group>
        <title ref="trm" symbol="off-warn">Terminal Mode</title>
        <title ref="cmd" symbol="off-warn">Computer Mode</title>
      </group>
      <repeat from="0" to="5">
        <group>
          <title ref="r$_">Running $_</title>
          <title ref="p$_">Pulse $_</title>
        </group>
      </repeat>
    </status>
  </object>
</adb>
