=== ciax/ciax-xml/schema/ddb.xsd
<?xml version="1.0" encoding="shift_jis"?>
<xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://www.w3.org/2001/XMLSchema" targetNamespace="http://ciax.sum.naoj.org/ciax-xml/ddb" xmlns:ddb="http://ciax.sum.naoj.org/ciax-xml/ddb">
  <!--Device database-->
  <xsd:include schemaLocation="range.xsd" />
  <xsd:include schemaLocation="repeat.xsd" />
  <xsd:include schemaLocation="param.xsd" />
  <xsd:element name="ddb">
    <xsd:complexType>
      <xsd:sequence>
        <xsd:element ref="ddb:device" minOccurs="1" maxOccurs="unbounded" />
      </xsd:sequence>
    </xsd:complexType>
  </xsd:element>
  <xsd:element name="device">
    <xsd:complexType>
      <xsd:sequence>
        <!--Protocol for RS232C-->
        <xsd:element ref="ddb:serial" minOccurs="0" maxOccurs="1" />
        <!--Command frame-->
        <xsd:element ref="ddb:cmdselect" minOccurs="1" maxOccurs="1"></xsd:element>
        <xsd:element ref="ddb:cmdccrange" minOccurs="0" maxOccurs="1"></xsd:element>
        <xsd:element ref="ddb:cmdframe" minOccurs="0" maxOccurs="1" />
        <!--Response frame-->
        <xsd:element ref="ddb:rspselect" minOccurs="1" maxOccurs="1"></xsd:element>
        <xsd:element ref="ddb:rspccrange" minOccurs="0" maxOccurs="1"></xsd:element>
        <xsd:element ref="ddb:rspframe" minOccurs="0" maxOccurs="1" />
      </xsd:sequence>
      <xsd:attribute name="id" type="xsd:string" use="required" />
      <xsd:attribute name="label" type="xsd:string" />
      <xsd:attribute name="reference" type="xsd:anyURI" />
      <xsd:attribute name="wait" type="xsd:float"></xsd:attribute>
    </xsd:complexType>
  </xsd:element>
  <xsd:element name="serial">
    <xsd:complexType>
      <xsd:attribute name="speed">
        <xsd:simpleType>
          <xsd:restriction base="xsd:double">
            <xsd:enumeration value="300" />
            <xsd:enumeration value="600" />
            <xsd:enumeration value="1200" />
            <xsd:enumeration value="2400" />
            <xsd:enumeration value="4800" />
            <xsd:enumeration value="9600" />
            <xsd:enumeration value="19200" />
            <xsd:enumeration value="38400" />
            <xsd:enumeration value="56000" />
            <xsd:enumeration value="57600" />
            <xsd:enumeration value="115200" />
            <xsd:enumeration value="230400" />
          </xsd:restriction>
        </xsd:simpleType>
      </xsd:attribute>
      <xsd:attribute name="databit">
        <xsd:simpleType>
          <xsd:restriction base="xsd:int">
            <xsd:minInclusive value="7" />
            <xsd:maxInclusive value="8" />
          </xsd:restriction>
        </xsd:simpleType>
      </xsd:attribute>
      <xsd:attribute name="parity">
        <xsd:simpleType>
          <xsd:restriction base="xsd:string">
            <xsd:enumeration value="NONE" />
            <xsd:enumeration value="EVEN" />
            <xsd:enumeration value="ODD" />
          </xsd:restriction>
        </xsd:simpleType>
      </xsd:attribute>
      <xsd:attribute name="stopbit">
        <xsd:simpleType>
          <xsd:restriction base="xsd:int">
            <xsd:minInclusive value="1" />
            <xsd:maxInclusive value="2" />
          </xsd:restriction>
        </xsd:simpleType>
      </xsd:attribute>
      <xsd:attribute name="flowctl">
        <xsd:simpleType>
          <xsd:restriction base="xsd:string">
            <xsd:enumeration value="NONE" />
            <xsd:enumeration value="XONXOFF" />
            <xsd:enumeration value="CTSRTS" />
          </xsd:restriction>
        </xsd:simpleType>
      </xsd:attribute>
    </xsd:complexType>
  </xsd:element>
  <!--Shared frame-->
  <xsd:element name="ccrange">
    <xsd:complexType></xsd:complexType>
  </xsd:element>
  <xsd:element name="selected">
    <xsd:complexType></xsd:complexType>
  </xsd:element>
  <xsd:simpleType name="codec">
    <xsd:restriction base="xsd:string">
      <xsd:enumeration value="chr" />
      <xsd:enumeration value="hexstr" />
      <xsd:enumeration value="bew" />
      <xsd:enumeration value="lew"></xsd:enumeration>
    </xsd:restriction>
  </xsd:simpleType>
  <xsd:simpleType name="ccmethod">
    <!--Check Code Method-->
    <xsd:restriction base="xsd:string">
      <xsd:enumeration value="bcc" />
      <xsd:enumeration value="sum" />
      <xsd:enumeration value="len" />
    </xsd:restriction>
  </xsd:simpleType>
  <!--Command Elements-->
  <xsd:element name="data">
    <xsd:complexType>
      <xsd:simpleContent>
        <xsd:extension base="xsd:string">
          <xsd:attribute name="label" type="xsd:string" />
          <xsd:attribute name="encode" type="ddb:codec"></xsd:attribute>
          <xsd:attribute name="format" type="xsd:string"></xsd:attribute>
          <xsd:attribute name="type">
            <xsd:simpleType>
              <xsd:restriction base="xsd:string">
                <xsd:enumeration value="text"></xsd:enumeration>
                <xsd:enumeration value="formula"></xsd:enumeration>
                <xsd:enumeration value="csv"></xsd:enumeration>
              </xsd:restriction>
            </xsd:simpleType>
          </xsd:attribute>
        </xsd:extension>
      </xsd:simpleContent>
    </xsd:complexType>
  </xsd:element>
  <!--Command Select-->
  <xsd:element name="cmdselect">
    <xsd:complexType>
      <xsd:sequence>
        <xsd:element ref="ddb:command" minOccurs="1" maxOccurs="unbounded" />
      </xsd:sequence>
    </xsd:complexType>
  </xsd:element>
  <xsd:element name="command">
    <xsd:complexType>
      <xsd:sequence>
        <xsd:element ref="ddb:parameters" minOccurs="0" maxOccurs="1" />
        <xsd:choice minOccurs="0" maxOccurs="unbounded">
          <xsd:element ref="ddb:data" />
          <xsd:element ref="ddb:repeat" />
        </xsd:choice>
      </xsd:sequence>
      <xsd:attribute name="id" type="xsd:string" use="required" />
      <xsd:attribute name="label" type="xsd:string" />
      <xsd:attribute name="response" type="xsd:string" />
      <xsd:attribute name="nocache" type="xsd:boolean" />
      <xsd:attribute name="type">
        <xsd:simpleType>
          <xsd:restriction base="xsd:string">
            <xsd:enumeration value="stat" />
            <xsd:enumeration value="action" />
            <xsd:enumeration value="config" />
          </xsd:restriction>
        </xsd:simpleType>
      </xsd:attribute>
    </xsd:complexType>
  </xsd:element>
  <xsd:element name="repeat">
    <xsd:complexType>
      <xsd:choice minOccurs="0" maxOccurs="unbounded">
        <xsd:element ref="ddb:data" />
      </xsd:choice>
      <xsd:attributeGroup ref="ddb:repeat" />
      <xsd:attribute name="delimiter" type="xsd:string" />
    </xsd:complexType>
  </xsd:element>
  <!--Command CC-->
  <xsd:element name="cmdccrange">
    <xsd:complexType>
      <xsd:choice minOccurs="0" maxOccurs="unbounded">
        <xsd:element ref="ddb:selected" />
        <xsd:element ref="ddb:data" />
      </xsd:choice>
      <xsd:attribute name="method" type="ddb:ccmethod"></xsd:attribute>
    </xsd:complexType>
  </xsd:element>
  <!--Command frame-->
  <xsd:element name="cmdframe">
    <xsd:complexType>
      <xsd:choice minOccurs="0" maxOccurs="unbounded">
        <xsd:element ref="ddb:data" />
        <xsd:element ref="ddb:selected" />
        <xsd:element ref="ddb:ccrange" />
      </xsd:choice>
    </xsd:complexType>
  </xsd:element>
  <!--Response Elements-->
  <xsd:attributeGroup name="rsp_attr">
    <xsd:attribute name="label" type="xsd:string" />
    <xsd:attribute name="assign" type="xsd:string" />
    <xsd:attribute name="verify" type="xsd:string" />
    <xsd:attribute name="decode" type="ddb:codec"></xsd:attribute>
    <xsd:attribute name="length" type="xsd:int" />
    <xsd:attribute name="slice" type="ddb:rerange" />
  </xsd:attributeGroup>
  <xsd:group name="rsp_elem">
    <xsd:choice>
      <xsd:element ref="ddb:field" />
      <xsd:element ref="ddb:array" />
    </xsd:choice>
  </xsd:group>
  <xsd:element name="field">
    <xsd:complexType>
      <xsd:attributeGroup ref="ddb:rsp_attr" />
    </xsd:complexType>
  </xsd:element>
  <xsd:element name="array">
    <xsd:complexType>
      <xsd:sequence>
        <xsd:element ref="ddb:index" minOccurs="1" maxOccurs="unbounded" />
      </xsd:sequence>
      <xsd:attributeGroup ref="ddb:rsp_attr" />
    </xsd:complexType>
  </xsd:element>
  <!--Field Elements-->
  <xsd:element name="index">
    <xsd:complexType>
      <xsd:attribute name="size" type="xsd:int" use="required" />
      <xsd:attribute name="range" type="xsd:string" use="required" />
    </xsd:complexType>
  </xsd:element>
  <!--Response Select-->
  <xsd:element name="rspselect">
    <xsd:complexType>
      <xsd:sequence>
        <xsd:element ref="ddb:response" minOccurs="1" maxOccurs="unbounded" />
      </xsd:sequence>
    </xsd:complexType>
  </xsd:element>
  <xsd:element name="response">
    <xsd:complexType>
      <xsd:choice>
        <xsd:group minOccurs="0" maxOccurs="unbounded" ref="ddb:rsp_elem"></xsd:group>
      </xsd:choice>
      <xsd:attribute name="id" type="xsd:string" use="required" />
      <xsd:attribute name="label" type="xsd:string" />
    </xsd:complexType>
  </xsd:element>
  <!--Response CC-->
  <xsd:element name="rspccrange">
    <xsd:complexType>
      <xsd:choice minOccurs="0" maxOccurs="unbounded">
        <xsd:element ref="ddb:selected" />
        <xsd:group ref="ddb:rsp_elem" />
      </xsd:choice>
      <xsd:attribute name="method" type="ddb:ccmethod" use="required"></xsd:attribute>
    </xsd:complexType>
  </xsd:element>
  <!--Response frame-->
  <xsd:element name="rspframe">
    <xsd:complexType>
      <xsd:choice minOccurs="0" maxOccurs="unbounded">
        <xsd:group ref="ddb:rsp_elem" />
        <xsd:element ref="ddb:selected" />
        <xsd:element ref="ddb:ccrange" />
      </xsd:choice>
      <xsd:attribute name="terminator" type="xsd:string" />
      <xsd:attribute name="delimiter" type="xsd:string" />
    </xsd:complexType>
  </xsd:element>
</xsd:schema>

=== ciax/ciax-xml/ddb-oss.xml
<?xml version="1.0" encoding="iso-8859-1"?>
<ddb xsi:schemaLocation="http://ciax.sum.naoj.org/ciax-xml/schema/ddb.xsd" xmlns="http://ciax.sum.naoj.org/ciax-xml/ddb" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
  <device id="oss" label="OSS Command line">
    <cmdselect>
      <command id="getstat" label="Get all status" response="getstat" type="stat">
        <data label="Status Command" text="OSSC_screenPrint -R" type="text" />
        <data label="InR Select(NsOpt/NsIR/Cas)" text=" TSCV.RotatorType" type="text" />
        <data label="Stow pin Status" text=" CXWS.TSCV.STOW_1" type="text" />
        <data label="Shutter Status" text=" CXWS.TSCV.SHUTTER" type="text" />
        <data label="AZ/EL Drive Status" text=" CXWS.TSCV.TELDRIVE" type="text" />
        <data label="EL Angle(deg)" text=" CXWS.TSCS.EL" type="text" />
        <data label="CIAX-MLP3 Comm Error" text=" CXWS.TSCV.CIAX_MLP3_FAULT" type="text" />
        <data label="InR Drive ON/OFF" text=" TSCV.InsRotRotation" type="text" />
        <data label="BOLT Status" text=" CXWS.TSCV.0_SENSOR" type="text" />
      </command>
      <command id="iststat" label="Get Instrument ID" response="iststat" type="stat">
        <data label="Status Command" text="OSSC_screenPrint -R" type="text" />
        <data label="CAS Instrument" text=" CXWS.TSCV.OBE_INR" type="text" />
      </command>
      <command id="jakstat" label="Jack Bolt Status" response="jakstat" type="stat">
        <data label="Status Command" text="OSSC_screenPrint -R" type="text" />
        <data label="Bolt Each Status" text=" CXWS.TSCV.POWER_V1" type="text" />
        <data label="Bolt Each Position" text=" CXWS.TSCV.POWER_V2" type="text" />
        <data label="Zsensor Each Position" text=" CXWS.TSCL.Z_SENSOR" type="text" />
      </command>
      <command id="inrstat" label="Cas InR Status" response="inrstat" type="stat">
        <data label="Status Command" text="OSSC_screenPrint -R" type="text" />
        <data label="InR Angle(deg)" text=" CXWS.TSCS.INSROT" type="text" />
      </command>
      <command id="logstat" label="Login Status" response="logstat" type="stat">
        <data label="Status Command" text="OSSC_screenPrint -R" type="text" />
        <data label="LOGIN 0" text=" TSCV.TSC.LOGIN0" type="text" />
        <data label="LOGIN 1" text=" TSCV.TSC.LOGIN1" type="text" />
        <data label="LOGIN 2" text=" TSCV.TSC.LOGIN2" type="text" />
        <data label="LOGIN 3" text=" TSCV.TSC.LOGIN3" type="text" />
      </command>
      <command id="getexit" label="Exit Code" response="exit" type="stat">
        <data text="cat $HOME/.var/exit.txt" type="text" />
      </command>
      <command id="login" label="TSC Login" response="exit">
        <data text="OSST_ciaxTSCcommand 10 'EXEC TSC NATIVE CMD=&quot;cccccc" type="text" />
        <data text="1A1901 " type="text" />
        <data text="ciax%%%%%%%%%%%%%%%% " type="text" />
        <data text="CIAX%%%%%%%%%%%% " type="text" />
        <data text="dummyunit dummyMenu dummyMessage" type="text" />
        <data text="&quot;';echo $?|tee $HOME/.var/exit.txt" type="text" />
      </command>
      <command id="logout" label="TSC Logout" response="exit">
        <data text="OSST_ciaxTSCcommand 10 'EXEC TSC NATIVE CMD=&quot;cccccc" type="text" />
        <data text="1A1902" type="text" />
        <data text="&quot;';echo $?|tee $HOME/.var/exit.txt" type="text" />
      </command>
      <command id="setinst" label="Set Instrument ID [0-12]" response="exit" type="config">
        <parameters>
          <par label="Inst ID [0-12]" range="1:12"></par>
        </parameters>
        <data text="OSST_ciaxTSCcommand 10 'EXEC TSC NATIVE CMD=&quot;cccccc" type="text" />
        <data text="13200700" type="text" />
        <data format="%02d" text="$1" type="formula" />
        <data text="&quot;';echo $?|tee $HOME/.var/exit.txt" type="text" />
      </command>
      <command id="config" label="Execute Config Command [code]" response="exit">
        <parameters>
          <par label="Command Code" pattern=".+"></par>
        </parameters>
        <data text="OSST_ciaxTSCcommand 10 'EXEC TSC NATIVE CMD=&quot;cccccc" type="text" />
        <data text="$1" type="formula" />
        <data text="&quot;';echo $?|tee $HOME/.var/exit.txt" type="text" />
      </command>
      <command id="ossact" label="Execute Action Command [code]" response="exit" type="action">
        <parameters>
          <par label="Command Code" pattern=".+"></par>
        </parameters>
        <data text="ossact" type="text" />
        <data text="$1" type="formula" />
      </command>
    </cmdselect>
    <cmdframe>
      <selected />
      <data encode="chr" label="Suffix" text="0xa" type="text" />
    </cmdframe>
    <rspselect>
      <response id="getstat">
        <field assign="rsel" label="InR Select(NsOpt/NsIR/Cas)" />
        <field assign="stow_1" decode="hexstr" label="Stow pin Status" />
        <field assign="shutter" label="Shutter Status" />
        <field assign="teldrive" label="AZ/EL Drive Status" />
        <field assign="el" label="EL Angle(deg)" />
        <field assign="mlp3" label="CIAX-MLP3 Comm Error" />
        <field assign="rpw" label="InR Drive ON/OFF" />
        <field assign="bstat" decode="hexstr" label="BOLT System Status" />
      </response>
      <response id="iststat">
        <field assign="iid" label="CAS Instrument" />
      </response>
      <response id="jakstat">
        <field assign="bsa" label="BOLT SUM ALM(POWER_V1)" length="2" />
        <field assign="cjb" label="ALL BOLT STAT(POWER_V1)" length="2" />
        <array assign="bl" label="Each Bolt Status(POWER_V1)" length="1">
          <index range="0:15" size="16" />
        </array>
        <array assign="be" label="Each Bolt Alarm(POWER_V1)" length="1">
          <index range="0:15" size="16" />
        </array>
        <field assign="mba" label="MLP3-BOLT COMM(POWER_V1)" length="2" />
        <field label="Cut off" />
        <field assign="bcl" label="BOLT CONTROL SOURCE(POWER_V1)" length="2" />
        <field assign="cjh" label="Jack Home(POWER_V1)" length="4" />
        <array assign="jk" label="Bolt Position(POWER_V2)" length="12">
          <index range="0:15" size="16" />
        </array>
        <array assign="zp" label="Zsensor Position" length="12" slice="2:4">
          <index range="0:3" size="4" />
        </array>
      </response>
      <response id="inrstat">
        <field assign="iang" label="InR Angle(deg)" />
      </response>
      <response id="logstat">
        <field assign="login0" label="LOGIN 0" />
        <field assign="login1" label="LOGIN 1" />
        <field assign="login2" label="LOGIN 2" />
        <field assign="login3" label="LOGIN 3" />
      </response>
      <response id="exit">
        <field assign="exit" label="Exit Code" />
      </response>
    </rspselect>
    <rspframe delimiter="\n">
      <selected />
    </rspframe>
  </device>
</ddb>

=== ciax/ciax-xml/ddb-bbe.xml
<?xml version='1.0' encoding='ISO-8859-1'?>
<ddb xsi:schemaLocation='http://ciax.sum.naoj.org/ciax-xml/schema/ddb.xsd' xmlns='http://ciax.sum.naoj.org/ciax-xml/ddb' xmlns:xsi='http://www.w3.org/2001/XMLSchema-instance'>
  <device id='bbe' label='BB Electric 232SDD16' wait='0.3'>
    <serial databit='8' flowctl='NONE' parity='NONE' speed='9600' stopbit='1'/>
    <cmdselect>
      <command id='getstat' label='Get Status' response='getstat' type='stat'>
        <data>RD</data>
      </command>
      <command id='defio' label='DEFINE IN/OUT' type='config'>
        <data>SD</data>
        <data encode='bew' label='msb'>0x1111</data>
      </command>
      <command id='output' label='OUTPUT [DDDDD]' type='action'>
        <parameters label='[0-65535]'>
          <par>
            <range>0:65535</range>
          </par>
        </parameters>
        <data>SO</data>
        <eval encode='bew'>"$1"</eval>
      </command>
    </cmdselect>
    <cmdframe>
      <data label='Prefix'>!0</data>
      <selected/>
    </cmdframe>
    <rspselect>
      <response id='getstat'>
        <field decode='bew'>
          <assign>stat</assign>
        </field>
      </response>
    </rspselect>
    <rspframe>
      <selected/>
    </rspframe>
  </device>
</ddb>

=== ciax/ciax-xml/ddb-fpa.xml
<?xml version='1.0' encoding='ISO-8859-1'?>
<ddb xsi:schemaLocation='http://ciax.sum.naoj.org/ciax-xml/schema/ddb.xsd' xmlns='http://ciax.sum.naoj.org/ciax-xml/ddb' xmlns:xsi='http://www.w3.org/2001/XMLSchema-instance'>
  <device id='fpa' label='Field Point Analog Input(FP-AI-100)' reference='http://ciax.sum.naoj.org/man/fieldpoint/fp-1000prm-321632c.pdf' wait='0'>
    <serial databit='8' flowctl='NONE' parity='NONE' speed='115200' stopbit='1'/>
    <cmdselect>
      <!--String Length must be <32-->
      <command id='getstat' label='Get status' response='getstat' type='stat'>
        <data type='text'>!F00FF</data>
      </command>
      <command id='setr1' label='Set range +-1.2V' response='default' type='config'>
        <data type='text'>!D00FF</data>
        <repeat from='1' to='8'>
          <data type='text'>0000107</data>
        </repeat>
      </command>
      <command id='setr6' label='Set range +-6V' response='default' type='config'>
        <data type='text'>!D00FF</data>
        <repeat from='1' to='8'>
          <data type='text'>0000105</data>
        </repeat>
      </command>
      <command id='setr15' label='Set range +-15V' response='default' type='config'>
        <data type='text'>!D00FF</data>
        <repeat from='1' to='8'>
          <data type='text'>0000112</data>
        </repeat>
      </command>
    </cmdselect>
    <cmdframe>
      <data label='Prefix' type='text'>&gt;01</data>
      <selected/>
      <data type='text'>??</data>
      <data encode='chr' type='text'>13</data>
      <data encode='chr' type='text'>10</data>
    </cmdframe>
    <rspselect>
      <response id='getstat'>
        <array assign='stat' decode='hexstr' label='Status' length='4'>
          <index range='0:7' size='8'/>
        </array>
      </response>
      <response id='default'/>
    </rspselect>
    <rspframe>
      <field label='Prefix' length='1' verify='A'/>
      <rspccrange method='sum'>
        <selected/>
      </rspccrange>
      <field assign='cc' decode='hexstr' label='BCC' length='2'/>
    </rspframe>
  </device>
</ddb>

=== ciax/ciax-xml/ddb-oma.xml
<?xml version='1.0' encoding='ISO-8859-1'?>
<ddb xsi:schemaLocation='http://ciax.sum.naoj.org/ciax-xml/schema/ddb.xsd' xmlns='http://ciax.sum.naoj.org/ciax-xml/ddb' xmlns:xsi='http://www.w3.org/2001/XMLSchema-instance'>
  <device id='oma' label='OMEGA Air Pressure Sensor(PX971)' wait='0.1'>
    <serial databit='8' flowctl='NONE' parity='NONE' speed='9600' stopbit='1'/>
    <cmdselect>
      <command id='getstat' label='Get Status' response='getstat' type='stat'>
        <data>00P1</data>
      </command>
    </cmdselect>
    <cmdframe>
      <data label='Prefix'>*</data>
      <selected/>
      <data encode='chr' label='Suffix'>0xd</data>
    </cmdframe>
    <rspselect>
      <response id='getstat'>
        <field length='5'>
          
          <verify>01CP=</verify>
        </field>
        <field length='6'>
          
          <assign>stat</assign>
        </field>
      </response>
    </rspselect>
    <rspframe terminator='\r'>
      <field label='Prefix' length='1'>
        
        <verify>?</verify>
      </field>
      <selected/>
    </rspframe>
  </device>
</ddb>
