=== ciax/ciax-xml/schema/ddb.xsd
<?xml version="1.0" encoding="shift_jis"?>
<xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://www.w3.org/2001/XMLSchema" targetNamespace="http://ciax.sum.naoj.org/ciax-xml/ddb" xmlns:ddb="http://ciax.sum.naoj.org/ciax-xml/ddb">
  <!--Device database-->
  <xsd:include schemaLocation="range.xsd" />
  <xsd:include schemaLocation="repeat.xsd" />
  <xsd:include schemaLocation="param.xsd" />
  <xsd:element name="ddb">
    <xsd:complexType>
      <xsd:sequence>
        <xsd:element ref="ddb:device" minOccurs="1" maxOccurs="unbounded" />
      </xsd:sequence>
    </xsd:complexType>
  </xsd:element>
  <xsd:element name="device">
    <xsd:complexType>
      <xsd:sequence>
        <!--Protocol for RS232C-->
        <xsd:element ref="ddb:serial" minOccurs="0" maxOccurs="1" />
        <!--Command frame-->
        <xsd:element ref="ddb:cmdselect" minOccurs="1" maxOccurs="1"></xsd:element>
        <xsd:element ref="ddb:cmdccrange" minOccurs="0" maxOccurs="1"></xsd:element>
        <xsd:element ref="ddb:cmdframe" minOccurs="0" maxOccurs="1" />
        <!--Response frame-->
        <xsd:element ref="ddb:rspselect" minOccurs="1" maxOccurs="1"></xsd:element>
        <xsd:element ref="ddb:rspccrange" minOccurs="0" maxOccurs="1"></xsd:element>
        <xsd:element ref="ddb:rspframe" minOccurs="0" maxOccurs="1" />
      </xsd:sequence>
      <xsd:attribute name="id" type="xsd:string" use="required" />
      <xsd:attribute name="label" type="xsd:string" />
      <xsd:attribute name="reference" type="xsd:anyURI" />
      <xsd:attribute name="wait" type="xsd:float"></xsd:attribute>
    </xsd:complexType>
  </xsd:element>
  <xsd:element name="serial">
    <xsd:complexType>
      <xsd:attribute name="speed">
        <xsd:simpleType>
          <xsd:restriction base="xsd:double">
            <xsd:enumeration value="300" />
            <xsd:enumeration value="600" />
            <xsd:enumeration value="1200" />
            <xsd:enumeration value="2400" />
            <xsd:enumeration value="4800" />
            <xsd:enumeration value="9600" />
            <xsd:enumeration value="19200" />
            <xsd:enumeration value="38400" />
            <xsd:enumeration value="56000" />
            <xsd:enumeration value="57600" />
            <xsd:enumeration value="115200" />
            <xsd:enumeration value="230400" />
          </xsd:restriction>
        </xsd:simpleType>
      </xsd:attribute>
      <xsd:attribute name="databit">
        <xsd:simpleType>
          <xsd:restriction base="xsd:int">
            <xsd:minInclusive value="7" />
            <xsd:maxInclusive value="8" />
          </xsd:restriction>
        </xsd:simpleType>
      </xsd:attribute>
      <xsd:attribute name="parity">
        <xsd:simpleType>
          <xsd:restriction base="xsd:string">
            <xsd:enumeration value="NONE" />
            <xsd:enumeration value="EVEN" />
            <xsd:enumeration value="ODD" />
          </xsd:restriction>
        </xsd:simpleType>
      </xsd:attribute>
      <xsd:attribute name="stopbit">
        <xsd:simpleType>
          <xsd:restriction base="xsd:int">
            <xsd:minInclusive value="1" />
            <xsd:maxInclusive value="2" />
          </xsd:restriction>
        </xsd:simpleType>
      </xsd:attribute>
      <xsd:attribute name="flowctl">
        <xsd:simpleType>
          <xsd:restriction base="xsd:string">
            <xsd:enumeration value="NONE" />
            <xsd:enumeration value="XONXOFF" />
            <xsd:enumeration value="CTSRTS" />
          </xsd:restriction>
        </xsd:simpleType>
      </xsd:attribute>
    </xsd:complexType>
  </xsd:element>
  <!--Shared frame-->
  <xsd:element name="ccrange">
    <xsd:complexType></xsd:complexType>
  </xsd:element>
  <xsd:element name="selected">
    <xsd:complexType></xsd:complexType>
  </xsd:element>
  <xsd:simpleType name="codec">
    <xsd:restriction base="xsd:string">
      <xsd:enumeration value="chr" />
      <xsd:enumeration value="hexstr" />
      <xsd:enumeration value="bew" />
      <xsd:enumeration value="lew"></xsd:enumeration>
    </xsd:restriction>
  </xsd:simpleType>
  <xsd:simpleType name="ccmethod">
    <!--Check Code Method-->
    <xsd:restriction base="xsd:string">
      <xsd:enumeration value="bcc" />
      <xsd:enumeration value="sum" />
      <xsd:enumeration value="len" />
    </xsd:restriction>
  </xsd:simpleType>
  <!--Command Elements-->
  <xsd:element name="data">
    <xsd:complexType>
      <xsd:simpleContent>
        <xsd:extension base="xsd:string">
          <xsd:attribute name="label" type="xsd:string" />
          <xsd:attribute name="encode" type="ddb:codec"></xsd:attribute>
          <xsd:attribute name="format" type="xsd:string"></xsd:attribute>
          <xsd:attribute name="type">
            <xsd:simpleType>
              <xsd:restriction base="xsd:string">
                <xsd:enumeration value="text"></xsd:enumeration>
                <xsd:enumeration value="formula"></xsd:enumeration>
                <xsd:enumeration value="csv"></xsd:enumeration>
              </xsd:restriction>
            </xsd:simpleType>
          </xsd:attribute>
        </xsd:extension>
      </xsd:simpleContent>
    </xsd:complexType>
  </xsd:element>
  <!--Command Select-->
  <xsd:element name="cmdselect">
    <xsd:complexType>
      <xsd:sequence>
        <xsd:element ref="ddb:command" minOccurs="1" maxOccurs="unbounded" />
      </xsd:sequence>
    </xsd:complexType>
  </xsd:element>
  <xsd:element name="command">
    <xsd:complexType>
      <xsd:sequence>
        <xsd:element ref="ddb:parameters" minOccurs="0" maxOccurs="1" />
        <xsd:choice minOccurs="0" maxOccurs="unbounded">
          <xsd:element ref="ddb:data" />
          <xsd:element ref="ddb:repeat" />
        </xsd:choice>
      </xsd:sequence>
      <xsd:attribute name="id" type="xsd:string" use="required" />
      <xsd:attribute name="label" type="xsd:string" />
      <xsd:attribute name="response" type="xsd:string" />
      <xsd:attribute name="nocache" type="xsd:boolean" />
      <xsd:attribute name="type">
        <xsd:simpleType>
          <xsd:restriction base="xsd:string">
            <xsd:enumeration value="stat" />
            <xsd:enumeration value="action" />
            <xsd:enumeration value="config" />
          </xsd:restriction>
        </xsd:simpleType>
      </xsd:attribute>
    </xsd:complexType>
  </xsd:element>
  <xsd:element name="repeat">
    <xsd:complexType>
      <xsd:choice minOccurs="0" maxOccurs="unbounded">
        <xsd:element ref="ddb:data" />
      </xsd:choice>
      <xsd:attributeGroup ref="ddb:repeat" />
      <xsd:attribute name="delimiter" type="xsd:string" />
    </xsd:complexType>
  </xsd:element>
  <!--Command CC-->
  <xsd:element name="cmdccrange">
    <xsd:complexType>
      <xsd:choice minOccurs="0" maxOccurs="unbounded">
        <xsd:element ref="ddb:selected" />
        <xsd:element ref="ddb:data" />
      </xsd:choice>
      <xsd:attribute name="method" type="ddb:ccmethod"></xsd:attribute>
    </xsd:complexType>
  </xsd:element>
  <!--Command frame-->
  <xsd:element name="cmdframe">
    <xsd:complexType>
      <xsd:choice minOccurs="0" maxOccurs="unbounded">
        <xsd:element ref="ddb:data" />
        <xsd:element ref="ddb:selected" />
        <xsd:element ref="ddb:ccrange" />
      </xsd:choice>
    </xsd:complexType>
  </xsd:element>
  <!--Response Elements-->
  <xsd:attributeGroup name="rsp_attr">
    <xsd:attribute name="label" type="xsd:string" />
    <xsd:attribute name="assign" type="xsd:string" />
    <xsd:attribute name="verify" type="xsd:string" />
    <xsd:attribute name="decode" type="ddb:codec"></xsd:attribute>
    <xsd:attribute name="length" type="xsd:int" />
    <xsd:attribute name="slice" type="ddb:rerange" />
  </xsd:attributeGroup>
  <xsd:group name="rsp_elem">
    <xsd:choice>
      <xsd:element ref="ddb:field" />
      <xsd:element ref="ddb:array" />
    </xsd:choice>
  </xsd:group>
  <xsd:element name="field">
    <xsd:complexType>
      <xsd:attributeGroup ref="ddb:rsp_attr" />
    </xsd:complexType>
  </xsd:element>
  <xsd:element name="array">
    <xsd:complexType>
      <xsd:sequence>
        <xsd:element ref="ddb:index" minOccurs="1" maxOccurs="unbounded" />
      </xsd:sequence>
      <xsd:attributeGroup ref="ddb:rsp_attr" />
    </xsd:complexType>
  </xsd:element>
  <!--Field Elements-->
  <xsd:element name="index">
    <xsd:complexType>
      <xsd:attribute name="size" type="xsd:int" use="required" />
      <xsd:attribute name="range" type="xsd:string" use="required" />
    </xsd:complexType>
  </xsd:element>
  <!--Response Select-->
  <xsd:element name="rspselect">
    <xsd:complexType>
      <xsd:sequence>
        <xsd:element ref="ddb:response" minOccurs="1" maxOccurs="unbounded" />
      </xsd:sequence>
    </xsd:complexType>
  </xsd:element>
  <xsd:element name="response">
    <xsd:complexType>
      <xsd:choice>
        <xsd:group minOccurs="0" maxOccurs="unbounded" ref="ddb:rsp_elem"></xsd:group>
      </xsd:choice>
      <xsd:attribute name="id" type="xsd:string" use="required" />
      <xsd:attribute name="label" type="xsd:string" />
    </xsd:complexType>
  </xsd:element>
  <!--Response CC-->
  <xsd:element name="rspccrange">
    <xsd:complexType>
      <xsd:choice minOccurs="0" maxOccurs="unbounded">
        <xsd:element ref="ddb:selected" />
        <xsd:group ref="ddb:rsp_elem" />
      </xsd:choice>
      <xsd:attribute name="method" type="ddb:ccmethod" use="required"></xsd:attribute>
    </xsd:complexType>
  </xsd:element>
  <!--Response frame-->
  <xsd:element name="rspframe">
    <xsd:complexType>
      <xsd:choice minOccurs="0" maxOccurs="unbounded">
        <xsd:group ref="ddb:rsp_elem" />
        <xsd:element ref="ddb:selected" />
        <xsd:element ref="ddb:ccrange" />
      </xsd:choice>
      <xsd:attribute name="terminator" type="xsd:string" />
      <xsd:attribute name="delimiter" type="xsd:string" />
    </xsd:complexType>
  </xsd:element>
</xsd:schema>

=== ciax/ciax-xml/ddb-cj2.xml
<?xml version='1.0' encoding='ISO-8859-1'?>
<ddb xsi:schemaLocation='http://ciax.sum.naoj.org/ciax-xml/schema/ddb.xsd' xmlns='http://ciax.sum.naoj.org/ciax-xml/ddb' xmlns:xsi='http://www.w3.org/2001/XMLSchema-instance'>
  <device id='cj2' label='OMRON CJ2M-CPU33'>
    <cmdselect>
      <command id='getstat' label='Get all status' response='getstat' type='stat'>
        <data encode='chr' label='FINS Command:MRC' type='text'>0x01</data>
        <data encode='chr' label='FINS Command:SRC' type='text'>0x01</data>
        <data encode='chr' label='FINS Param:Memory type(W)' type='text'>0xB1</data>
        <data encode='chr' label='FINS Param:Start Address(H)' type='text'>0x00</data>
        <data encode='chr' label='FINS Param:Start Address(L)' type='text'>0x0A</data>
        <data encode='chr' label='FINS Param:Bit Number' type='text'>0x00</data>
        <data encode='chr' label='FINS Param:Data Length (H)' type='text'>0x00</data>
        <data encode='chr' label='FINS Param:Data Length (L)' type='text'>0x14</data>
      </command>
      <command id='getzerr' label='Get Z Sensor Error' response='getzerr' type='stat'>
        <data encode='chr' label='FINS Command:MRC' type='text'>0x01</data>
        <data encode='chr' label='FINS Command:SRC' type='text'>0x01</data>
        <data encode='chr' label='FINS Param:Memory type(D)' type='text'>0x82</data>
        <data encode='chr' label='FINS Param:Start Address(H)' type='text'>0x00</data>
        <data encode='chr' label='FINS Param:Start Address(L)' type='text'>0x00</data>
        <data encode='chr' label='FINS Param:Bit Number' type='text'>0x00</data>
        <data encode='chr' label='FINS Param:Data Length (H)' type='text'>0x00</data>
        <data encode='chr' label='FINS Param:Data Length (L)' type='text'>0x01</data>
      </command>
      <command id='getzlen' label='Get Z Sensor Length' response='getzlen' type='stat'>
        <data encode='chr' label='FINS Command:MRC' type='text'>0x01</data>
        <data encode='chr' label='FINS Command:SRC' type='text'>0x01</data>
        <data encode='chr' label='FINS Param:Memory type(D)' type='text'>0x82</data>
        <data encode='chr' label='FINS Param:Start Address(H)' type='text'>0x00</data>
        <data encode='chr' label='FINS Param:Start Address(L)' type='text'>0x0A</data>
        <data encode='chr' label='FINS Param:Bit Number' type='text'>0x00</data>
        <data encode='chr' label='FINS Param:Data Length (H)' type='text'>0x00</data>
        <data encode='chr' label='FINS Param:Data Length (L)' type='text'>0x0A</data>
      </command>
      <command id='setbit' label='Set Bit' response='cmdrsp' type='stat'>
        <parameters>
          <par label='Address [0-3]' validate='range'>0:3</par>
          <par label='Bit [0-15]' validate='range'>0:15</par>
        </parameters>
        <data encode='chr' label='FINS Command:MRC' type='text'>0x01</data>
        <data encode='chr' label='FINS Command:SRC' type='text'>0x02</data>
        <data encode='chr' label='FINS Param:Memory type(W)' type='text'>0x31</data>
        <data encode='chr' label='FINS Param:Start Address(H)' type='text'>0x00</data>
        <data encode='chr' label='FINS Param:Start Address(L)' type='formula'>$1</data>
        <data encode='chr' label='FINS Param:Bit Number' type='formula'>$2</data>
        <data encode='chr' label='FINS Param:Bit Data Length (H)' type='text'>0x00</data>
        <data encode='chr' label='FINS Param:Bit Data Length (L)' type='text'>0x01</data>
        <data encode='chr' label='FINS Param:Bit Data' type='text'>0x01</data>
      </command>
      <command id='clrbit' label='Clear All Bit' response='cmdrsp' type='stat'>
        <data encode='chr' label='FINS Command:MRC' type='text'>0x01</data>
        <data encode='chr' label='FINS Command:SRC' type='text'>0x02</data>
        <data encode='chr' label='FINS Param:Memory type(W)' type='text'>0xB1</data>
        <data encode='chr' label='FINS Param:Start Address(H)' type='text'>0x00</data>
        <data encode='chr' label='FINS Param:Start Address(L)' type='formula'>0x00</data>
        <data encode='chr' label='FINS Param:Bit Number' type='formula'>0x00</data>
        <data encode='chr' label='FINS Param:Data Length (H)' type='text'>0x00</data>
        <data encode='chr' label='FINS Param:Data Length (L)' type='text'>0x03</data>
        <data encode='bew' label='FINS Param:Bit Data' type='text'>0x00</data>
        <data encode='bew' label='FINS Param:Bit Data' type='text'>0x00</data>
        <data encode='bew' label='FINS Param:Bit Data' type='text'>0x00</data>
      </command>
    </cmdselect>
    <cmdframe>
      <data encode='chr' label='FINS Header:ICF' type='text'>0x80</data>
      <data encode='chr' label='FINS Header:RSV' type='text'>0x00</data>
      <data encode='chr' label='FINS Header:GCT' type='text'>0x02</data>
      <data encode='chr' label='FINS Header:DNA' type='text'>0x00</data>
      <data encode='chr' label='FINS Header:DA1' type='text'>100<!--DST IP address--></data>
      <data encode='chr' label='FINS Header:DA2' type='text'>0x00</data>
      <data encode='chr' label='FINS Header:SNA' type='text'>0x00</data>
      <data encode='chr' label='FINS Header:SA1' type='text'>57<!--SRC IP address--></data>
      <data encode='chr' label='FINS Header:SA2' type='text'>0x00</data>
      <data encode='chr' label='FINS Header:SID' type='text'>0xFF</data>
      <selected/>
    </cmdframe>
    <rspselect>
      <response id='getstat'>
        <field decode='chr' label='FINS Command:MRC' length='1' verify='0x01'/>
        <field decode='chr' label='FINS Command:SRC' length='1' verify='0x01'/>
        <field decode='chr' label='FINS Command:MRES' length='1' verify='0x00'/>
        <field decode='chr' label='FINS Command:SRES' length='1' verify='0x00'/>
        <array assign='w' decode='bew' label='Status' length='2'>
          <index range='0:19' size='20'/>
        </array>
      </response>
      <response id='getzerr'>
        <field decode='chr' label='FINS Command:MRC' length='1' verify='0x01'/>
        <field decode='chr' label='FINS Command:SRC' length='1' verify='0x01'/>
        <field decode='chr' label='FINS Command:MRES' length='1' verify='0x00'/>
        <field decode='chr' label='FINS Command:SRES' length='1' verify='0x00'/>
        <field assign='zerr' decode='bew' label='FINS Command:Z sensor error' length='2'/>
      </response>
      <response id='getzlen'>
        <field decode='chr' label='FINS Command:MRC' length='1' verify='0x01'/>
        <field decode='chr' label='FINS Command:SRC' length='1' verify='0x01'/>
        <field decode='chr' label='FINS Command:MRES' length='1' verify='0x00'/>
        <field decode='chr' label='FINS Command:SRES' length='1' verify='0x00'/>
        <array assign='d' decode='bew' label='Status' length='2'>
          <index range='0:9' size='8'/>
        </array>
      </response>
      <response id='cmdrsp' label='command resp'>
        <field decode='chr' label='FINS Command:MRC' length='1' verify='0x01'/>
        <field decode='chr' label='FINS Command:SRC' length='1' verify='0x02'/>
        <field decode='chr' label='FINS Command:MRES' length='1' verify='0x00'/>
        <field decode='chr' label='FINS Command:SRES' length='1' verify='0x00'/>
      </response>
    </rspselect>
    <rspframe>
      <field decode='chr' label='FINS Header:ICF' length='1' verify='0xc0'/>
      <field decode='chr' label='FINS Header:RSV' length='1' verify='0x00'/>
      <field decode='chr' label='FINS Header:GCT' length='1' verify='0x02'/>
      <field decode='chr' label='FINS Header:DNA' length='1' verify='0x00'/>
      <field decode='chr' label='FINS Header:DA1' length='1' verify='57'/>
      <field decode='chr' label='FINS Header:DA2' length='1' verify='0x00'/>
      <field decode='chr' label='FINS Header:SNA' length='1' verify='0x00'/>
      <field decode='chr' label='FINS Header:SA1' length='1' verify='100'/>
      <field decode='chr' label='FINS Header:SA2' length='1' verify='0x00'/>
      <field decode='chr' label='FINS Header:SID' length='1' verify='0xFF'/>
      <selected/>
    </rspframe>
  </device>
</ddb>

=== ciax/ciax-xml/ddb-lk8.xml
<?xml version='1.0' encoding='ISO-8859-1'?>
<ddb xsi:schemaLocation='http://ciax.sum.naoj.org/ciax-xml/schema/ddb.xsd' xmlns='http://ciax.sum.naoj.org/ciax-xml/ddb' xmlns:xsi='http://www.w3.org/2001/XMLSchema-instance'>
  <device id='lk8' label='Lakeshore MODEL 340 8CH' wait='0.3'>
    <serial databit='7' flowctl='NONE' parity='NONE' speed='9600' stopbit='1'/>
    <cmdselect>
      <command id='getstat' label='Get Status' response='getstat' type='stat'>
        <data text='krdg? c1;' type='text'/>
        <data text='krdg? c2;' type='text'/>
        <data text='krdg? c3;' type='text'/>
        <data text='krdg? c4;' type='text'/>
        <data text='krdg? d1;' type='text'/>
        <data text='krdg? d2;' type='text'/>
        <data text='krdg? d3;' type='text'/>
        <data text='krdg? d4;' type='text'/>
      </command>
      <command id='htrstat' label='Heater Power (%)' response='htrstat' type='stat'>
        <data text='HTR?' type='text'/>
      </command>
      <command id='spstat' label='Set Point (K)' response='spstat' type='stat'>
        <data text='SETP? 1' type='text'/>
      </command>
    </cmdselect>
    <cmdframe>
      <selected/>
      <data encode='bew' label='Suffix' text='0x0d0a' type='text'/>
    </cmdframe>
    <rspselect>
      <response id='getstat'>
        <array assign='ch'>
          <index range='0:7' size='8'/>
        </array>
      </response>
      <response id='htrstat'>
        <field assign='htr'/>
      </response>
      <response id='spstat'>
        <field assign='sp'/>
      </response>
    </rspselect>
    <rspframe delimiter=';' terminator='\r\n'>
      <selected/>
    </rspframe>
  </device>
</ddb>

=== ciax/ciax-xml/ddb-k3n.xml
<?xml version='1.0' encoding='ISO-8859-1'?>
<ddb xsi:schemaLocation='http://ciax.sum.naoj.org/ciax-xml/schema/ddb.xsd' xmlns='http://ciax.sum.naoj.org/ciax-xml/ddb' xmlns:xsi='http://www.w3.org/2001/XMLSchema-instance'>
  <device id='k3n' label='OMRON K3NR' wait='1'>
    <serial databit='7' flowctl='NONE' parity='EVEN' speed='9600' stopbit='2'/>
    <cmdselect>
      <command id='getstat' label='Get Status' response='getstat' type='stat'>
        <data label='Node No.' text='00' type='text'/>
        <data label='Sub Address' text='00' type='text'/>
        <data label='SID' text='0' type='text'/>
        <data label='MRC' text='01' type='text'/>
        <data label='SRC' text='01' type='text'/>
        <data label='Variable type' text='C0' type='text'/>
        <data label='Start Address' text='0000' type='text'/>
        <data label='Void' text='00' type='text'/>
        <data label='Number of element' text='0001' type='text'/>
      </command>
    </cmdselect>
    <cmdccrange method='bcc'>
      <selected/>
      <data encode='chr' label='Suffix' text='3' type='text'/>
    </cmdccrange>
    <cmdframe>
      <data encode='chr' label='Prefix' text='2' type='text'/>
      <ccrange/>
      <data encode='chr' text='${cc}' type='formula'/>
    </cmdframe>
    <rspselect>
      <response id='getstat'>
        <field label='MRC SRC' length='4' verify='0101'/>
        <field assign='rcode' label='Response Code' length='4'/>
        <field assign='stat' label='Status' length='8'/>
      </response>
    </rspselect>
    <rspccrange method='bcc'>
      <field label='Node' length='4' verify='0000'/>
      <field assign='ecode' label='Exit Code' length='2'/>
      <selected/>
      <field decode='chr' label='Suffix' length='1' verify='3'/>
    </rspccrange>
    <rspframe>
      <field decode='chr' label='Prefix' length='1' verify='2'/>
      <ccrange/>
      <field assign='cc' decode='chr' label='BCC' length='1'/>
    </rspframe>
  </device>
</ddb>
